### ISSUE TITLE
Specify yubikey otp profile does not work anymore?

### ISSUE THREAD

**Issue by jeroenjacobs79** [blimmer/zsh-aws-vault#34]
Either my brain is pulling tricks on my, but I seem to remember I could specify the yubiky OTP profile to use on the zsh-aws-vault shortcuts like `avsh`.

eg, this is my `.aws/config` file:

```
[default]
region=eu-west-1

[profile hic]
mfa_serial=arn:aws:iam::xxxxxx:mfa/jeroen

[profile hic-admin]
source_profile = hic
role_arn = arn:aws:iam::xxxxxx:role/hic-admin-role
mfa_serial=arn:aws:iam::xxxxxx:mfa/jeroen
```

On my Yubikey, I have an OTP profile called `hic-aws-user` , and I verified this working correctly.

Shouldn't I be able to just type something like `avsh hic-admin hic-aws-user`, and It would get OTP key automatically and start the shell for the `hic-admin` profile?

```
avsh hic-admin hic-aws-user
aws-vault: error: exec: Couldn't find the executable 'hic-aws-user': exec: "hic-aws-user": executable file not found in $PATH
```

I really seem to have a memory of this working in the past, so either this is a false memory or I am missing something obvious?

env vars:

```
AWS_VAULT_BACKEND=pass
AWS_VAULT_PASS_PREFIX=aws-vault
AWS_VAULT_PL_BROWSER=''
AWS_VAULT_PL_BROWSER_LAUNCH_OPTS=''
AWS_VAULT_PL_DEFAULT_PROFILE=default
AWS_VAULT_PL_MFA=yubikey
```

**Comment by blimmer** [comment]
Hey @jeroenjacobs79 - I don't personally authenticate with a yubikey, so I'm not familiar with this workflow.

## `avsh` / `avli` explanation

That said, the convenience functions just pass the values through to the `aws-vault` executable. So, for example, here's what's happening for you when you run `avsh`: https://github.com/blimmer/zsh-aws-vault/blob/main/zsh-aws-vault.plugin.zsh#L27-L29

So if you're running this command:

```
avsh hic-admin hic-aws-user
```

it's equivalent to:

```
aws-vault exec --prompt ykman hic-admin hic-aws-user -- zsh
```

Here's the help docs for that command:

```
> aws-vault --version
v6.6.0
> aws-vault exec --help
usage: aws-vault exec [<flags>] <profile> [<cmd>] [<args>...]

Executes a command with AWS credentials in the environment
```

Based on that usage information, the error message you posted makes sense. It's interpreting `hic-aws-user` as the command (`<cmd>` from the help docs) you want to run.

## What Changed

The only thing I can think of that changed somewhat recently is https://github.com/blimmer/zsh-aws-vault/pull/29, which now passes all the additional parameters through. So, before, if you ran:

```
avsh hic-admin hic-aws-user
```

It would have been equivalent to:

```
aws-vault exec --prompt ykman hic-admin -- zsh
```

Because `hic-aws-user` would have been ignored. It's possible that this accounts for the change you're seeing.

## Docs

I'd recommend checking out the aws-vault Yubikey documentation to learn more about how to set up your token correctly: https://github.com/99designs/aws-vault/blob/master/USAGE.md#using-a-yubikey

Hopefully that helps! I don't think there's anything necessarily wrong with this plugin, so I will mark this issue as closed. Please feel free to reopen if I missed something.
